version: "3.0"
services:
  spring-demo:
    image: spring-boot-app
    ports:
      - "9292:9090"
    networks:
      - spring-boot-mysql
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8
    networks:
      - spring-boot-mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb  

networks:
  spring-boot-mysql: